const QUERY = {
  CONFIG: {
    GET_CONFIG: "GET_CONFIG",
  },
  ML_QUERY: {
    GET_MODELS: "GET_MODELS",
    GET_IMAGE_MODELS: "GET_IMAGE_MODELS",
  },
  AI_CONVERSATION: {
    GET_CONVERSATION: "GET_CONVERSATION",
    GET_CONVERSATIONS: "GET_CONVERSATIONS",
    GET_STATS: "GET_STATS",
  },
  SUMMARY: {
    GET_SUMMARY: "GET_SUMMARY",
  },
  AI_MODEL: {
    GET_MODELS: "GET_MODELS",
    GET_MODEL: "GET_MODEL",
    GET_STATS: "GET-STATS",
  },
  PROJECT: {
    GET_PROJECTS: "GET_PROJECTS",
    GET_PROJECT: "GET_PROEJECT",
  },
};

export default QUERY;
